"""测试增强指纹 (nc, w, h, xMin) 是否能区分所有10个glyph"""
import base64
from io import BytesIO
from fontTools.ttLib import TTFont

font1_b64 = "AAEAAAAKAIAAAwAgT1MvMmE5U8oAAAEoAAAAYGNtYXAAYACWAAABrAAAAEBnbHlmsAwePwAAAgQAAAXoaGVhZCfU9GAAAACsAAAANmhoZWEDPgFjAAAA5AAAACRobXR4CSQAJAAAAYgAAAAkbG9jYQdDCK8AAAHsAAAAGG1heHAAEABHAAABCAAAACBuYW1lOhdcVwAAB+wAAAKqcG9zdAADAAAAAAqYAAAAIAABAAADAAEAlwTqFV8PPPUACwIAAAAAAN4nCbQAAAAA5hSpKv/7/+ABgAGlAAAACAACAAAAAAAAAAEAAAHA/8AAAAGf//v//AGAAAEAAAAAAAAAAAAAAAAAAAAHAAEAAAALAEUAAwAAAAAAAQAAAAEAAQAAAAAAAAAAAAAABAFIA4QABQAAAUwBZgAAAEcBTAFmAAAA9QAZAIQAAAIACgMAAAAAAAAAAAABAAAAAAAAAAAAAAAAQVdTTQGAADAAOQHA/8AAAAHAAEAAAAABAAAAAAE5AaUAAAAAAAABnwAyAUAAAAEA//4BQP/7AUD//wGA//wBQP/+AAAAAAAAAAAAAAABAAMAAQAAAAwABAA0AAAABAAEAAEAAAA5//8AAAAw//8AAAABAAQAAAAFAAcACgACAAQACQAIAAEABgADAAAAEwBUAIwA0gEnAWwBvgIMAjcCpQL0AAIAMgAAAW0BpQADAAcAADMRIRElMxEjMgE7/vfX1wGl/lsyAUEAAgAA/+EBQAGgABMAJwAAEwYHMQYHFRYXFhc2NzY3NSYnJicTBgcxBgcmJyYnNTY3NjcWFxYXFaBELS0CAi0tREQtLQICLS1EYAEbGykpGxsBARsbKSkbGwEBoAItLUR/RC0tAgItLUR/RC0tAv7gKRsbAQEbGymAKRsbAQEbGymAAAH//v/gAQABpQAkAAAhFAcxBiMjIicmNTQ3NjMzEQcGJyYnJjc2Nzc2FxYXETMyFxYVAQAJCQ7ADgkJCQkOQC4MDA0IBwMCC2AQERABQA4JCQ4JCQkJDg4JCQEkHwcDAgsMDA0IQAoJCRP+oAkJDgAB//v/4AFAAaEAKwAAIRQHMQYjISYnJjc3Njc2JyYnJgcHBicmJyY3Njc3NhcWFxYHBgcHMzIXFhUBQAkJDv8AFQkHD8EYAgEVFyQjGiMLDQwKCQEBCSMtQD8pJQIDKoiwDgkJDgkJARMUD7kYIB8bGwIBGCAJAQEJCw0MCh8qAgUvLjk4KoIJCQ4AAAH////gAUABoAA3AAAlBgcxBgcjIicmJyY3Njc2FxYXFhczNjc2NyYnJicjJicmNzcjIicmNTQ3NjMzFhcWBwczFhcWFwFAAScmOlAkGxsLBAUGDQ0LDAQLHlAfFBQBARQUH2gVCQcPhJ4OCQkJCQ7wFQkHD4QWOScmAmg6JicBFBQhDQwLBQQGBgwcAgEUFB8fFBQBARMVD3gJCQ4OCQkBExUPeAEnJjoAAf/8/+ABgAGiAC8AACUUBzEGIyMVFAcGIyInJjU1IyInJjcTNjc2FxYXFgcHMzU0NzYzMhcWFRUzFhcWFQGACQkOIAkJDg4JCeARCgkHgAYMDA0MBAQFaq0JCQ4OCQkgDgkJcg4JCVIOCQkJCQ5SDw8PAQ8MBAQFBgwMDeCODgkJCQkOjgEJCQ0AAf/+/+ABQAGgADUAACUGBzEGByMiJyYnJjc2NzYXFhcWFzM2NzY3JicmJyMiJyY3NzY3MzIXFhUUBwYjIwczFhcWFwFAAScmOVAkHBwLBAUGDQ0LDAQMH1AeFBQBARQUHpkPCgkDIAYZwA4JCQkJDqUVczkmJwFnOSYnARQUIg0MCwUEBgYNHAIBFBQeHxQUAQsMDrIYAgkJDg4JCXECJiY6AAACAAD/4AFAAaAAHQAvAAATNzYnJicmIyIHBgcGBwYHBhUWFxYXNjc2NyYnJicHJicxJic2NzY3FhcWFwYHBgeoQAkBAQoKCw4KIRowHBsLCwItLURELS0CAiorQQgpGxsBARsbKSkbGwEBGxspAR9MCw0MCQgLJx43IyMaGh9ELS0CAi0tREIsLQT/ARsbKSkaGwEBGxsoKBwbAQABAAD/4AFEAaAAGAAAAQMGIyInJicmNxMjIicmNTQ3NjMhFhcWBwE84AoSCAgMAwMGxMgOCQkJCQ4BABIKCAgBcP6AEAQHDQwMAVAJCQ4OCQkBDxAQAAMAAP/gAUABoAAeADEARAAAJTY3JicmJyMGBwYHFhcGBwYVFhcWFzM2NzY3NCcmJyczFhcWFwYHBgcjJicmJzY3NjcTIyYnJic2NzY3MxYXFhcGBwYHAQwjAQElJDYgNiQlAQEjGA4OASUkNkA2JCUBDg4YfCAbEhIBARISGyAbEhIBARISGzBAGxISAQESEhtAGxISAQESEhvHJDU2JCUBASUkNjUkEhsaIDYkJQEBJSQ2IBobEpkBEhIbGxISAQESEhsbEhIB/sABEhIbGxISAQESEhsbEhIBAAACAAD/4AFAAaAAHgAwAAATBgcxBgcWFxYXBwYXFhcWMzI3Njc2NzY3NjUmJyYnESYnMSYnNjc2NxYXFhcGBwYHoEQtLQICKitBQAkBAQoKCw4KIRoxGxsLCwItLUQpGxsBARsbKSkbGwEBGxspAaACLS1EQiwtBEwLDQwJCAsnHjcjIxoaH0QtLQL/AAEbGygoHBsBARsbKSkaGwEAAAAACwCKAAMAAQQJAAAANAAAAAMAAQQJAAEAMgA0AAMAAQQJAAIADgBmAAMAAQQJAAMAUgB0AAMAAQQJAAQAMgA0AAMAAQQJAAUAeADGAAMAAQQJAAYALAE+AAMAAQQJAAoAWAFqAAMAAQQJAAsALgHCAAMAAQQJABAAJgHwAAMAAQQJABEACgIWAEMAbwBwAHkAcgBpAGcAaAB0ACAAKABjACkAIABGAG8AbgB0ACAAQQB3AGUAcwBvAG0AZQBGAG8AbgB0ACAAQQB3AGUAcwBvAG0AZQAgADYAIABGAHIAZQBlACAAUwBvAGwAaQBkAFIAZQBnAHUAbABhAHIARgBvAG4AdAAgAEEAdwBlAHMAbwBtAGUAIAA2ACAARgByAGUAZQAgAFMAbwBsAGkAZAA6AFYAZQByAHMAaQBvAG4AIAA3ADYAOAAuADAAMAA0AFYAZQByAHMAaQBvAG4AIAA3ADYAOAAuADAAMAA0ADsASgB1AGwAeQAgADEAMAAsACAAMgAwADIANQA7AEYAbwBuAHQAQwByAGUAYQB0AG8AcgAgADEANQAuADAALgAwAC4AMwAwADIANAAgADYANAAtAGIAaQB0AEYAbwBuAHQAQQB3AGUAcwBvAG0AZQA2AEYAcgBlAGUALQBTAG8AbABpAGQAVABoAGUAIAB3AGUAYgAnAHMAIABtAG8AcwB0ACAAcABvAHAAdQBsAGEAcgAgAGkAYwBvAG4AIABzAGUAdAAgAGEAbgBkACAAdABvAG8AbABrAGkAdAAuAGgAdAB0AHAAcwA6AC8ALwBmAG8AbgB0AGEAdwBlAHMAbwBtAGUALgBjAG8AbQBGAG8AbgB0ACAAQQB3AGUAcwBvAG0AZQAgADYAIABGAHIAZQBlAFMAbwBsAGkAZAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

f_bytes = base64.b64decode(font1_b64)
font = TTFont(BytesIO(f_bytes))
cmap = font.getBestCmap()
glyf = font["glyf"]

print("Full glyph features (nc, w, h, xMin, coords_count):")
header = "{:<6} {:<4} {:<6} {:<6} {:<8} {:<8} {:<8} {:<8} {:<8}".format(
    "Char", "nc", "w", "h", "xMin", "yMin", "xMax", "yMax", "coords")
print(header)
print("-" * len(header))

fingerprints = {}
for char in "0123456789":
    gn = cmap.get(ord(char))
    if gn:
        g = glyf[gn]
        coords, _, _ = g.getCoordinates(glyf) if hasattr(g, "getCoordinates") else (None, None, None)
        nc = g.numberOfContours
        w = g.xMax - g.xMin
        h = g.yMax - g.yMin
        n_coords = len(coords) if coords is not None else 0
        print("{:<6} {:<4} {:<6} {:<6} {:<8} {:<8} {:<8} {:<8} {:<8}".format(
            char, nc, w, h, g.xMin, g.yMin, g.xMax, g.yMax, n_coords))
        # Test: use (nc, w, h, xMin) as fingerprint
        finger4 = (nc, w, h, g.xMin)
        if finger4 in fingerprints:
            print("  ** DUPLICATE with char {} **".format(fingerprints[finger4]))
        fingerprints[finger4] = char

font.close()

print()
print("Unique 4-feature fingerprints:", len(fingerprints))
if len(fingerprints) == 10:
    print("SUCCESS: (nc, w, h, xMin) uniquely identifies all 10 glyphs!")
else:
    print("Need more features, only {} unique fingerprints".format(len(fingerprints)))
    # Try adding coords_count
    print("Check if coords_count helps...")
