const fs = require('fs'), path = require('path'), canvasLib = require('canvas');
const wasmBuf = fs.readFileSync(path.join(__dirname, 'program.wasm'));
let gc=[undefined,null,true,false,0,function(){},null,{createElement(t){if(t==='canvas'){let w=300,h=150;const c=canvasLib.createCanvas(w,h);const ctx=c.getContext('2d');return{get width(){return w},set width(v){w=v;c.width=v},get height(){return h},set height(v){h=v;c.height=v},getContext(){return ctx},toDataURL(m){return c.toDataURL(m||'image/png')},addEventListener(){},removeEventListener(){},_rc:c}},return{tagName:t.toUpperCase(),width:120,height:150,getContext(){return null},addEventListener(){},removeEventListener(){}}},addEventListener(){},removeEventListener(){}}];
let dc=gc.length;const kc=[];let hc,pc,rc;
const bc=c=>c,fc=c=>{gc[dc]=c;return dc++},lc=c=>c,qc=c=>gc[c];
const mc={0:c=>bc(qc(c).length),8:()=>{const img={src:'',onload:null,width:0,height:0,naturalWidth:0,naturalHeight:0,_decoded:null,addEventListener(){},removeEventListener(){}};Object.defineProperty(img,'src',{get(){return img._src||''},set(v){img._src=v;img.complete=true;if(v&&v.startsWith('data:image')){try{const b=v.split(',')[1];const buf=Buffer.from(b,'base64');if(canvasLib){const ci=new canvasLib.Image();ci.src=buf;img.naturalWidth=ci.width;img.naturalHeight=ci.height;img.width=img.width||ci.width;img.height=img.height||ci.height;img._decoded=ci}}catch(e){}}if(typeof img.onload==='function')setTimeout(()=>img.onload(),0)},configurable:true});return fc(img)},9:c=>bc(qc(c).width),10:c=>bc(qc(c).height),11:(c,a)=>{qc(c).width=lc(a)},12:(c,a)=>{qc(c).height=lc(a)},13:(c,a)=>{qc(c).src=qc(a)},14:(c,a,n)=>{const d=qc(c),w=lc(a),h=lc(n);if(canvasLib)return fc(new canvasLib.ImageData(d,w,h));return fc({data:new Uint8ClampedArray(w*h*4),width:w,height:h})},15:c=>fc(qc(c).data),17:(c,a,n,t,e)=>fc(qc(c).getImageData(lc(a),lc(n),lc(t),lc(e))),18:(c,a,n,t)=>bc(qc(c).putImageData(qc(a),lc(n),lc(t))),19:(c,a,n,t)=>bc(qc(c).drawImage(qc(a),lc(n),lc(t))),22:(c,a)=>fc(qc(c).getContext(qc(a))),23:(c,a)=>fc(qc(c).createElement(qc(a))),27:c=>bc(1),10001:()=>{gc[dc]=undefined;return dc++},10002:c=>{gc[c]=undefined},10003:(c,a)=>{gc[c]=gc[a]},10010:(c,a)=>{gc[dc]=gc[c][gc[a]];return dc++},10011:(c,a,n)=>{gc[c][gc[a]]=gc[n]},10020:c=>+(!gc[c]),10030:c=>{gc[dc]=c;return dc++},10031:c=>+gc[c],10032:(c,a)=>{gc[c]=a},10033:c=>{gc[dc]=!!c;return dc++},10034:(c,a)=>gc[c]===gc[a],10040:(c,a)=>{let n='';for(let t=c;t<c+a;t++)n+=String.fromCharCode(hc[t]);gc[dc]=n;return dc++},10041:()=>{let c='',a=rc;for(;;){const n=34^hc[a++];if(!n)break;c+=String.fromCharCode(n)}gc[dc]=c;return dc++},10050:c=>{gc[dc]=kc[c];return dc++},10051:()=>kc.length,10060:(c,a)=>{const s=gc[c];for(let t=0;t<s.length;t++)hc[a+t]=s.charCodeAt(t);return s.length},10061:(c,a,n,t)=>{gc[c].set(hc.subarray(n,n+t),a)},10062:(c,a,n,t)=>{gc[c].subarray(a,a+n).set(hc.subarray(t,t+n))},10063:(c,a)=>{gc[dc]=new Uint8ClampedArray(hc.buffer,c,a);return dc++},10070:c=>{gc[dc]=function(){kc.length=0;for(let i=0;i<arguments.length;i++)kc.push(arguments[i]);gc[4]=this;const s=dc;pc(0,c,0);dc=s};return dc++},20000:c=>console.log(gc[c]),30000:()=>{}};
(async()=>{
const m=await WebAssembly.compile(wasmBuf);const i=await WebAssembly.instantiate(m,{a:mc});hc=new Uint8Array(i.exports.memory.buffer);pc=i.exports[0];i.exports._initialize();rc=pc(1);const n=gc.length;pc(2);dc=n;
const doc=gc[7];
const keys=Object.keys(doc).filter(k=>k.startsWith('__'));
console.error('Functions:',keys.join(', '));
for(let i=8;i<gc.length;i++){if(gc[i]!==undefined)console.error('gc['+i+']:',typeof gc[i],typeof gc[i]==='function'?'fn':typeof gc[i]==='string'?'"'+gc[i].slice(0,40)+'"':'');}
})();
